export const WEAPONS = {
  spudgun: {
    name: 'Spudgun',
    description: 'Trusty starter sidearm. Reliable hit, semi-auto. Always at your hip as your secondary.',
    crosshair: 'cross-small',
    adsCrosshair: 'iron-post',
    damage: 26,
    fireRate: 0.32,
    magSize: 12,
    reserve: 60,
    reloadTime: 1.4,
    spread: 0.012,
    adsSpread: 0.003,
    projectileSpeed: 80,
    projectileSize: 0.1,
    projectileColor: 0xffce5e,
    auto: false,
    pellets: 1,
    viewmodelColor: 0x8b5a2b,
    zoomFOV: 52,
    zoomMoveMult: 0.7,
    moveSpeedMult: 1.15,   // pistol — light, brisk
    recoilPitch: 0.085,
    recoilYaw: 0.022,
    recoilRecover: 9,
    kickAmt: 0.10,        // viewmodel kick-back on fire (visual)
    shakeAmt: 0.045,      // camera shake on fire
  },
  fryer: {
    name: 'Fry-er',
    description: 'Full-auto assault rifle. Hot stream of crispy bits — control your bursts and keep your aim flat. T: Sizzle Burst — 3-round burst, zero spread, 12s cooldown.',
    crosshair: 'cross',
    adsCrosshair: 'red-dot',
    special: { name: 'Sizzle Burst', kind: 'burst', cooldown: 12, shots: 3, gap: 0.05, spread: 0 },
    damage: 12,
    fireRate: 0.08,
    magSize: 30,
    reserve: 120,
    reloadTime: 2.4,        // bumped from 2.0 — heavier rifle feels deliberate
    spread: 0.04,
    adsSpread: 0.012,
    projectileSpeed: 95,
    projectileSize: 0.06,
    projectileColor: 0xf6c265,
    auto: true,
    pellets: 1,
    viewmodelColor: 0xc47a3d,
    zoomFOV: 56,
    zoomMoveMult: 0.6,
    moveSpeedMult: 0.96,    // a touch slower — full-auto rifle weight
    recoilPitch: 0.065,     // was 0.042 — climb is now noticeable
    recoilYaw: 0.045,       // was 0.032
    recoilRecover: 6.5,     // was 7 — recovers a bit slower
    kickAmt: 0.12,          // was 0.07 — viewmodel shoves harder
    shakeAmt: 0.060,        // was 0.035 — camera judder per shot
  },
  hashbrowner: {
    name: 'Hashbrowner',
    description: 'Pellet shotgun — eight crispy fragments per pull. Devastating up close, useless past 14m. T: Slug Shot — next pull fires a single high-damage slug, 10s cooldown.',
    crosshair: 'circle',
    adsCrosshair: 'shotgun-arcs',
    special: { name: 'Slug Shot', kind: 'slug', cooldown: 10, damage: 95, projectileSize: 0.16 },
    damage: 10,
    fireRate: 0.85,
    magSize: 6,
    reserve: 24,
    reloadTime: 2.6,
    spread: 0.13,
    adsSpread: 0.06,
    projectileSpeed: 75,
    projectileSize: 0.07,
    projectileColor: 0xb8693a,
    auto: false,
    pellets: 8,
    viewmodelColor: 0x6b3a1d,
    zoomFOV: 65,
    zoomMoveMult: 0.6,
    moveSpeedMult: 0.92,   // pump shotgun — bulky
    recoilPitch: 0.18,
    recoilYaw: 0.05,
    recoilRecover: 8,
    kickAmt: 0.20,
    shakeAmt: 0.10,
  },
  masher: {
    name: 'Masher',
    description: 'Double-barrel buckshot — 9 pellets, 2 shells per mag, fast reload. Get in their face and pull. T: Quick Fire — empties both barrels back-to-back, 12s cooldown.',
    crosshair: 'circle-large',
    adsCrosshair: 'rib-bead',
    special: { name: 'Quick Fire', kind: 'burst', cooldown: 12, shots: 2, gap: 0.09 },
    damage: 18,
    fireRate: 0.7,
    magSize: 2,
    reserve: 12,
    reloadTime: 1.5,
    spread: 0.14,
    adsSpread: 0.07,
    projectileSpeed: 130,
    projectileSize: 0.09,
    projectileColor: 0xfff4d6,
    auto: false,
    pellets: 9,
    viewmodelColor: 0x4a2c1a,
    zoomFOV: 60,
    zoomMoveMult: 0.55,
    moveSpeedMult: 0.88,   // double-barrel — heavy, in-your-face
    recoilPitch: 0.24,
    recoilYaw: 0.06,
    recoilRecover: 7,
    kickAmt: 0.24,
    shakeAmt: 0.13,
  },
  spudling: {
    name: 'Spudling Gun',
    description: 'Belt-fed heavy machine gun. Tiny per-bullet damage but pinpoint accuracy — and a punch that builds the longer you hold. P: Sentry — locked, no reload, 4× fire rate, 2× damage, 15s cooldown. T: Hot Barrel — 2× fire rate for 3s, 15s cooldown.',
    crosshair: 'smg',
    adsCrosshair: 'holo',
    special: { name: 'Hot Barrel', kind: 'hotBarrel', cooldown: 15, duration: 3.0, fireRateMult: 0.5 },
    damage: 4,
    fireRate: 0.06,
    magSize: 60,
    reserve: 180,
    reloadTime: 5.2,       // was 4.5 — belt feed takes its time
    spread: 0.008,
    adsSpread: 0.002,
    projectileSpeed: 100,
    projectileSize: 0.07,
    projectileColor: 0xffd97a,
    auto: true,
    pellets: 1,
    viewmodelColor: 0x2a2018,
    zoomFOV: 50,
    zoomMoveMult: 0.40,    // was 0.45 — heavier when scoped
    moveSpeedMult: 0.92,   // was 1.05 — heavy MG, not nimble
    recoilPitch: 0.048,    // was 0.022 — climbs with sustained fire
    recoilYaw: 0.050,      // was 0.026 — drifts wider too
    recoilRecover: 5.5,    // was 7 — settles slower
    kickAmt: 0.13,         // was 0.05 — meaty shove
    shakeAmt: 0.055,       // was 0.022 — sustained judder
  },
  boomstick: {
    name: 'Boomstick',
    description: 'Bolt-action sniper. One shot, one mash — slow chamber, slower walk. The muzzle blast blinds, shoves and shakes you. T: Steady Breath — next shot has no flash, no shake, low recoil, 10s cooldown.',
    crosshair: 'dot',
    special: { name: 'Steady Breath', kind: 'steady', cooldown: 10 },
    damage: 115,
    fireRate: 1.5,         // was 1.1 — slower between bolt cycles
    magSize: 5,
    reserve: 20,
    reloadTime: 4.2,       // was 3.5 — longer reload arc
    spread: 0.0,
    adsSpread: 0.0,
    projectileSpeed: 260,
    projectileSize: 0.13,
    projectileColor: 0xe8b85c,
    auto: false,
    pellets: 1,
    viewmodelColor: 0x6b4a2a,
    zoomFOV: 11,
    zoomMoveMult: 0.26,    // was 0.32 — barely creeps when scoped
    moveSpeedMult: 0.72,   // was 0.82 — heavy, deliberate walk
    scope: true,
    recoilPitch: 0.48,     // was 0.32 — savage kick up
    recoilYaw: 0.020,      // was 0.015
    recoilRecover: 3.5,    // was 5 — long re-settle after each shot
    kickAmt: 0.52,         // was 0.34 — viewmodel pumps back
    shakeAmt: 0.18,        // was 0.0 — now adds camera shake too
  },
  tossor: {
    name: 'Tater Tosser',
    description: 'Grenade launcher. Lobbed explosive arcs over cover — slow, heavy, big radius. T: Triple Tater — next pull lobs 3 grenades in a fan, 15s cooldown.',
    crosshair: 'arc',
    adsCrosshair: 'leaf',
    special: { name: 'Triple Tater', kind: 'fan', cooldown: 15, count: 3, spread: 0.05 },
    damage: 90,
    fireRate: 1.0,
    magSize: 4,
    reserve: 12,
    reloadTime: 3.0,
    spread: 0.0,
    adsSpread: 0.0,
    projectileSpeed: 38,
    projectileSize: 0.18,
    projectileColor: 0xc47a3d,
    auto: false,
    pellets: 1,
    gravity: 12,
    explosionRadius: 5.5,
    impactExplode: true,
    viewmodelColor: 0x3a2a1a,
    zoomFOV: 60,
    zoomMoveMult: 0.5,
    moveSpeedMult: 0.78,   // grenade launcher — heaviest
    recoilPitch: 0.14,
    recoilYaw: 0.04,
    recoilRecover: 6,
    kickAmt: 0.16,
    shakeAmt: 0.07,
  },
  knife: {
    name: 'Spud Knife',
    description: 'Silent close-range execution — 70 damage swing, ~3m reach, no ammo, no mercy. Always available as slot 3.',
    crosshair: 'x',
    damage: 70,
    fireRate: 0.45,
    magSize: 1,
    reserve: 0,
    reloadTime: 0,
    spread: 0,
    adsSpread: 0,
    projectileSpeed: 0,
    projectileSize: 0,
    projectileColor: 0xc0b8a8,
    auto: false,
    pellets: 1,
    melee: true,
    range: 3.2,
    viewmodelColor: 0xc0b8a8,
    zoomFOV: 78,
    zoomMoveMult: 1.0,
    moveSpeedMult: 1.20,   // knife — lightest, fastest
    recoilPitch: 0.02,
    recoilYaw: 0.005,
    recoilRecover: 8,
  },
};

export const WEAPON_ORDER = ['spudgun', 'fryer', 'hashbrowner', 'masher', 'spudling', 'boomstick', 'tossor'];
export const BASE_FOV = 78;
